---
spring:
  application:
    name: @name@
  profiles: business-service-1
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost-1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
server:
  port: 8071
info:
  app.name: @name@
  jdk.version: @java.version@
  build.artifactId: @project.artifactId@
  build.version: @project.version@
management:
  endpoint:
    health:
      show-details: always

---
spring:
  application:
    name: @name@
  profiles: business-service-2
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost-2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 8072

info:
  app.name: @name@
  jdk.version: @java.version@
  build.artifactId: @project.artifactId@
  build.version: @project.version@

management:
  endpoint:
    health:
      show-details: always